# Generated by Django 3.2.9 on 2021-11-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepi', '0002_auto_20211113_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculdades',
            name='curso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculdades',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faculdades',
            name='notaenade',
            field=models.FloatField(),
        ),
    ]
