# Generated by Django 3.2.9 on 2021-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepi', '0003_auto_20211115_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculdades',
            name='notaenade',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='faculdades',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
